In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/문화예술체육소비시군구별시설수.csv')

In [3]:
df_seoul = df[df['SIGNGU_NM'].str.contains('서울특별시')]
df_seoul['자치구'] = df_seoul['SIGNGU_NM'].str.split().str[1]
df_seoul

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\1741743188.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul['자치구'] = df_seoul['SIGNGU_NM'].str.split().str[1]

     LCLAS_NM MLSFC_NM  SIGNGU_NM  FCLTY_CO  자치구
0        문화예술     공연시설  서울특별시 종로구       329  종로구
1        문화예술     공연시설   서울특별시 중구       104   중구
2        문화예술     공연시설  서울특별시 용산구       149  용산구
3        문화예술     공연시설  서울특별시 성동구       165  성동구
4        문화예술     공연시설  서울특별시 광진구        78  광진구
...       ...      ...        ...       ...  ...
3913       소비     기타소비  서울특별시 관악구       597  관악구
3914       소비     기타소비  서울특별시 서초구       388  서초구
3915       소비     기타소비  서울특별시 강남구       728  강남구
3916       소비     기타소비  서울특별시 송파구       811  송파구
3917       소비     기타소비  서울특별시 강동구       637  강동구

[450 rows x 5 columns]

In [4]:
df_seoul['MLSFC_NM'].unique()

array(['공연시설', '전시시설', '지역문화시설', '학교/교육기관', '문화예술서비스', '생활스포츠시설',
       '전문스포츠시설', '스포츠서비스업', '공원', '관광지', '동/식물원/휴양림', '휴식시설/서비스', '음식소비',
       '패션/미용소비', '개인/생활용품소비', '대형소비시설', '기타소비'], dtype=object)

In [5]:
df_seoul_공연시설 = df_seoul[df_seoul['MLSFC_NM'].str.contains('공연시설')]
df_seoul_공연시설

   LCLAS_NM MLSFC_NM   SIGNGU_NM  FCLTY_CO   자치구
0      문화예술     공연시설   서울특별시 종로구       329   종로구
1      문화예술     공연시설    서울특별시 중구       104    중구
2      문화예술     공연시설   서울특별시 용산구       149   용산구
3      문화예술     공연시설   서울특별시 성동구       165   성동구
4      문화예술     공연시설   서울특별시 광진구        78   광진구
5      문화예술     공연시설  서울특별시 동대문구        21  동대문구
6      문화예술     공연시설   서울특별시 중랑구        21   중랑구
7      문화예술     공연시설   서울특별시 성북구        73   성북구
8      문화예술     공연시설   서울특별시 강북구        20   강북구
9      문화예술     공연시설   서울특별시 도봉구        16   도봉구
10     문화예술     공연시설   서울특별시 노원구        24   노원구
11     문화예술     공연시설   서울특별시 은평구        35   은평구
12     문화예술     공연시설  서울특별시 서대문구        68  서대문구
13     문화예술     공연시설   서울특별시 마포구       507   마포구
14     문화예술     공연시설   서울특별시 양천구        46   양천구
15     문화예술     공연시설   서울특별시 강서구        97   강서구
16     문화예술     공연시설   서울특별시 구로구        52   구로구
17     문화예술     공연시설   서울특별시 금천구        41   금천구
18     문화예술     공연시설  서울특별시 영등포구       145  영등포구
19     문화예술     공연시설   서울특별시 동작구        44   동작구
20     문화예술     공연시설   서울특별시 관악구        44   관악구
21     문화예술     공연시설   서울특별시 서초구       416   서초구
22     문화예술     공연시설   서울특별시 강남구      1374   강남구
23     문화예술     공연시설   서울특별시 송파구        97   송파구
24     문화예술     공연시설   서울특별시 강동구        38   강동구

In [6]:
df_seoul_공연시설.rename(columns={'FCLTY_CO':'공연시설수'})

   LCLAS_NM MLSFC_NM   SIGNGU_NM  공연시설수   자치구
0      문화예술     공연시설   서울특별시 종로구    329   종로구
1      문화예술     공연시설    서울특별시 중구    104    중구
2      문화예술     공연시설   서울특별시 용산구    149   용산구
3      문화예술     공연시설   서울특별시 성동구    165   성동구
4      문화예술     공연시설   서울특별시 광진구     78   광진구
5      문화예술     공연시설  서울특별시 동대문구     21  동대문구
6      문화예술     공연시설   서울특별시 중랑구     21   중랑구
7      문화예술     공연시설   서울특별시 성북구     73   성북구
8      문화예술     공연시설   서울특별시 강북구     20   강북구
9      문화예술     공연시설   서울특별시 도봉구     16   도봉구
10     문화예술     공연시설   서울특별시 노원구     24   노원구
11     문화예술     공연시설   서울특별시 은평구     35   은평구
12     문화예술     공연시설  서울특별시 서대문구     68  서대문구
13     문화예술     공연시설   서울특별시 마포구    507   마포구
14     문화예술     공연시설   서울특별시 양천구     46   양천구
15     문화예술     공연시설   서울특별시 강서구     97   강서구
16     문화예술     공연시설   서울특별시 구로구     52   구로구
17     문화예술     공연시설   서울특별시 금천구     41   금천구
18     문화예술     공연시설  서울특별시 영등포구    145  영등포구
19     문화예술     공연시설   서울특별시 동작구     44   동작구
20     문화예술     공연시설   서울특별시 관악구     44   관악구
21     문화예술     공연시설   서울특별시 서초구    416   서초구
22     문화예술     공연시설   서울특별시 강남구   1374   강남구
23     문화예술     공연시설   서울특별시 송파구     97   송파구
24     문화예술     공연시설   서울특별시 강동구     38   강동구

In [10]:
df_seoul_공연시설.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

KeyError: "['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'] not found in axis"

In [12]:
df_seoul_공연시설.rename(columns={'FCLTY_CO':'공연시설수'}, inplace=True)

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\4197466784.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_공연시설.rename(columns={'FCLTY_CO':'공연시설수'}, inplace=True)

In [14]:
df_seoul_공연시설 = df_seoul_공연시설.reindex(['자치구', '공연시설수'], axis=1)

In [15]:
df_seoul_공연시설

     자치구  공연시설수
0    종로구    329
1     중구    104
2    용산구    149
3    성동구    165
4    광진구     78
5   동대문구     21
6    중랑구     21
7    성북구     73
8    강북구     20
9    도봉구     16
10   노원구     24
11   은평구     35
12  서대문구     68
13   마포구    507
14   양천구     46
15   강서구     97
16   구로구     52
17   금천구     41
18  영등포구    145
19   동작구     44
20   관악구     44
21   서초구    416
22   강남구   1374
23   송파구     97
24   강동구     38

In [17]:
df_seoul_전시시설 = df_seoul[df_seoul['MLSFC_NM'].str.contains('전시시설')]
df_seoul_전시시설.rename(columns={'FCLTY_CO':'전시시설수'}, inplace=True)
df_seoul_전시시설.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_전시시설 = df_seoul_전시시설.reindex(['자치구', '전시시설수'], axis=1)
df_seoul_전시시설

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\3126388676.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_전시시설.rename(columns={'FCLTY_CO':'전시시설수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\3126388676.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_전시시설.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

      자치구  전시시설수
229   종로구    176
230    중구    126
231   용산구    104
232   성동구     95
233   광진구    115
234  동대문구    140
235   중랑구    116
236   성북구    173
237   강북구    106
238   도봉구    118
239   노원구    205
240   은평구    185
241  서대문구    129
242   마포구    133
243   양천구    149
244   강서구    210
245   구로구    167
246   금천구     80
247  영등포구    165
248   동작구    171
249   관악구    196
250   서초구    196
251   강남구    267
252   송파구    258
253   강동구    169

In [21]:
df_seoul_지역문화시설 = df_seoul[df_seoul['MLSFC_NM'].str.contains('지역문화시설')]
df_seoul_지역문화시설.rename(columns={'FCLTY_CO':'지역문화시설수'}, inplace=True)
df_seoul_지역문화시설.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_지역문화시설 = df_seoul_지역문화시설.reindex(['자치구', '지역문화시설수'], axis=1)
df_seoul_지역문화시설

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\2102249093.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_지역문화시설.rename(columns={'FCLTY_CO':'지역문화시설수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\2102249093.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_지역문화시설.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

      자치구  지역문화시설수
458   종로구       67
459    중구       26
460   용산구       11
461   성동구       13
462   광진구       19
463  동대문구       14
464   중랑구       22
465   성북구       39
466   강북구       22
467   도봉구       43
468   노원구       38
469   은평구       35
470  서대문구       29
471   마포구       16
472   양천구       29
473   강서구       33
474   구로구       20
475   금천구       27
476  영등포구       13
477   동작구       18
478   관악구       23
479   서초구       18
480   강남구       27
481   송파구       26
482   강동구       20

In [24]:
df_seoul_학교_교육기관 = df_seoul[df_seoul['MLSFC_NM'].str.contains('학교/교육기관')]
df_seoul_학교_교육기관.rename(columns={'FCLTY_CO':'학교/교육기관 수'}, inplace=True)
df_seoul_학교_교육기관.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_학교_교육기관 = df_seoul_학교_교육기관.reindex(['자치구', '학교/교육기관 수'], axis=1)
df_seoul_학교_교육기관

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\281068488.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_학교_교육기관.rename(columns={'FCLTY_CO':'학교/교육기관 수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\281068488.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_학교_교육기관.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

       자치구  학교/교육기관 수
687    종로구        160
688     중구        112
689    용산구        112
690    성동구        156
691    광진구        171
692   동대문구        174
693    중랑구        147
694    성북구        260
695    강북구        106
696    도봉구        146
697    노원구        304
698    은평구        193
699   서대문구        174
700    마포구        177
701    양천구        184
702    강서구        245
703    구로구        176
704    금천구         97
705   영등포구        165
706    동작구        180
707    관악구        179
708    서초구        202
709    강남구        247
710    송파구        267
711    강동구        180
1603   종로구        168
1604    중구        116
1605   용산구        131
1606   성동구        185
1607   광진구        236
1608  동대문구        210
1609   중랑구        193
1610   성북구        314
1611   강북구        126
1612   도봉구        171
1613   노원구        342
1614   은평구        233
1615  서대문구        195
1616   마포구        215
1617   양천구        230
1618   강서구        324
1619   구로구        236
1620   금천구        121
1621  영등포구        217
1622   동작구        216
1623   관악구        244
1624   서초구        272
1625   강남구        334
1626   송파구        353
1627   강동구        242

In [25]:
df_seoul_공원 = df_seoul[df_seoul['MLSFC_NM'].str.contains('공원')]
df_seoul_공원.rename(columns={'FCLTY_CO':'공원 수'}, inplace=True)
df_seoul_공원.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_공원 = df_seoul_공원.reindex(['자치구', '공원 수'], axis=1)
df_seoul_공원

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\3508745772.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_공원.rename(columns={'FCLTY_CO':'공원 수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\3508745772.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_공원.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

       자치구  공원 수
2061   종로구    85
2062    중구    95
2063   용산구   102
2064   성동구    92
2065   광진구    80
2066  동대문구   100
2067   중랑구   123
2068   성북구    62
2069   강북구   109
2070   도봉구    97
2071   노원구   228
2072   은평구   136
2073  서대문구   124
2074   마포구   134
2075   양천구   138
2076   강서구   257
2077   구로구   100
2078   금천구    91
2079  영등포구   144
2080   동작구   110
2081   관악구   151
2082   서초구   155
2083   강남구   198
2084   송파구   256
2085   강동구   166

In [26]:
df_seoul_관광지 = df_seoul[df_seoul['MLSFC_NM'].str.contains('관광지')]
df_seoul_관광지.rename(columns={'FCLTY_CO':'관광지 수'}, inplace=True)
df_seoul_관광지.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_관광지 = df_seoul_관광지.reindex(['자치구', '관광지 수'], axis=1)
df_seoul_관광지

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\1174697969.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_관광지.rename(columns={'FCLTY_CO':'관광지 수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\1174697969.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_관광지.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

       자치구  관광지 수
2290   종로구    151
2291    중구      4
2292   용산구      4
2293   성동구      4
2294   광진구     12
2295  동대문구      6
2296   중랑구      4
2297   성북구      7
2298   강북구     10
2299   도봉구      3
2300   노원구      9
2301   은평구     12
2302  서대문구      3
2303   마포구      8
2304   양천구      3
2305   강서구      2
2306   구로구      2
2307   금천구      1
2308  영등포구      5
2309   동작구      3
2310   관악구      5
2311   서초구      3
2312   강남구      2
2313   송파구     12
2314   강동구      3

In [27]:
df_seoul_동식물원_휴양림 = df_seoul[df_seoul['MLSFC_NM'].str.contains('동/식물원/휴양림')]
df_seoul_동식물원_휴양림.rename(columns={'FCLTY_CO':'동/식물원/휴양림 수'}, inplace=True)
df_seoul_동식물원_휴양림.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_동식물원_휴양림 = df_seoul_동식물원_휴양림.reindex(['자치구', '동/식물원/휴양림 수'], axis=1)
df_seoul_동식물원_휴양림

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\4043710869.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_동식물원_휴양림.rename(columns={'FCLTY_CO':'동/식물원/휴양림 수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\4043710869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_동식물원_휴양림.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

       자치구  동/식물원/휴양림 수
2519   종로구            6
2520    중구            6
2521   용산구            2
2522   성동구            1
2523   광진구            1
2524  동대문구            0
2525   중랑구            0
2526   성북구            1
2527   강북구            3
2528   도봉구            1
2529   노원구            2
2530   은평구            1
2531  서대문구            1
2532   마포구            1
2533   양천구            0
2534   강서구            1
2535   구로구            2
2536   금천구            0
2537  영등포구            1
2538   동작구            0
2539   관악구            0
2540   서초구            4
2541   강남구            6
2542   송파구            1
2543   강동구            3

In [28]:
df_seoul_음식소비 = df_seoul[df_seoul['MLSFC_NM'].str.contains('음식소비')]
df_seoul_음식소비.rename(columns={'FCLTY_CO':'음식점 수'}, inplace=True)
df_seoul_음식소비.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_음식소비 = df_seoul_음식소비.reindex(['자치구', '음식점 수'], axis=1)
df_seoul_음식소비

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\3637623244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_음식소비.rename(columns={'FCLTY_CO':'음식점 수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\3637623244.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_음식소비.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

       자치구  음식점 수
2977   종로구   6442
2978    중구   6363
2979   용산구   5693
2980   성동구   5278
2981   광진구   6227
2982  동대문구   6064
2983   중랑구   5107
2984   성북구   5789
2985   강북구   4712
2986   도봉구   3810
2987   노원구   5473
2988   은평구   5884
2989  서대문구   5008
2990   마포구   9470
2991   양천구   4744
2992   강서구   8160
2993   구로구   6073
2994   금천구   4568
2995  영등포구   8541
2996   동작구   4459
2997   관악구   6969
2998   서초구   8133
2999   강남구  15139
3000   송파구   9811
3001   강동구   6555

In [29]:
df_seoul_패션미용소비 = df_seoul[df_seoul['MLSFC_NM'].str.contains('패션/미용소비')]
df_seoul_패션미용소비.rename(columns={'FCLTY_CO':'패션/미용소비 수'}, inplace=True)
df_seoul_패션미용소비.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_패션미용소비 = df_seoul_패션미용소비.reindex(['자치구', '패션/미용소비 수'], axis=1)
df_seoul_패션미용소비

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\1662181318.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_패션미용소비.rename(columns={'FCLTY_CO':'패션/미용소비 수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\1662181318.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_패션미용소비.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

       자치구  패션/미용소비 수
3206   종로구       2207
3207    중구       4489
3208   용산구       1612
3209   성동구       1505
3210   광진구       2235
3211  동대문구       2089
3212   중랑구       2072
3213   성북구       2147
3214   강북구       1545
3215   도봉구       1441
3216   노원구       2246
3217   은평구       2289
3218  서대문구       1461
3219   마포구       2449
3220   양천구       2020
3221   강서구       2817
3222   구로구       2010
3223   금천구       1822
3224  영등포구       2629
3225   동작구       1514
3226   관악구       2477
3227   서초구       3056
3228   강남구       5937
3229   송파구       3408
3230   강동구       2683

In [30]:
df_seoul_대형소비시설 = df_seoul[df_seoul['MLSFC_NM'].str.contains('대형소비시설')]
df_seoul_대형소비시설.rename(columns={'FCLTY_CO':'대형소비시설 수'}, inplace=True)
df_seoul_대형소비시설.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)
df_seoul_대형소비시설 = df_seoul_대형소비시설.reindex(['자치구', '대형소비시설 수'], axis=1)
df_seoul_대형소비시설

C:\Users\morat\AppData\Local\Temp\ipykernel_58260\3095012450.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_대형소비시설.rename(columns={'FCLTY_CO':'대형소비시설 수'}, inplace=True)
C:\Users\morat\AppData\Local\Temp\ipykernel_58260\3095012450.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_seoul_대형소비시설.drop(['LCLAS_NM', 'MLSFC_NM', 'SIGNGU_NM'], axis=1, inplace=True)

       자치구  대형소비시설 수
3664   종로구         3
3665    중구       108
3666   용산구         4
3667   성동구         4
3668   광진구         7
3669  동대문구         8
3670   중랑구         2
3671   성북구        21
3672   강북구         8
3673   도봉구         1
3674   노원구        23
3675   은평구         6
3676  서대문구        28
3677   마포구         2
3678   양천구         5
3679   강서구         3
3680   구로구        10
3681   금천구        10
3682  영등포구        25
3683   동작구         2
3684   관악구         6
3685   서초구        28
3686   강남구       142
3687   송파구        30
3688   강동구         8

In [34]:
df_seoul_공연시설.set_index('자치구', inplace=True)
df_seoul_공연시설

      공연시설수
자치구
종로구     329
중구      104
용산구     149
성동구     165
광진구      78
동대문구     21
중랑구      21
성북구      73
강북구      20
도봉구      16
노원구      24
은평구      35
서대문구     68
마포구     507
양천구      46
강서구      97
구로구      52
금천구      41
영등포구    145
동작구      44
관악구      44
서초구     416
강남구    1374
송파구      97
강동구      38

In [35]:
df_seoul_전시시설.set_index('자치구', inplace=True)
df_seoul_지역문화시설.set_index('자치구', inplace=True)
df_seoul_관광지.set_index('자치구', inplace=True)
df_seoul_공원.set_index('자치구', inplace=True)
df_seoul_동식물원_휴양림.set_index('자치구', inplace=True)
df_seoul_음식소비.set_index('자치구', inplace=True)
df_seoul_패션미용소비.set_index('자치구', inplace=True)
df_seoul_대형소비시설.set_index('자치구', inplace=True)

In [38]:
result = pd.concat([df_seoul_공연시설, df_seoul_전시시설, df_seoul_관광지, df_seoul_공원, df_seoul_동식물원_휴양림, df_seoul_음식소비, df_seoul_패션미용소비,
                    df_seoul_대형소비시설], axis=1)
result

      공연시설수  전시시설수  관광지 수  공원 수  동/식물원/휴양림 수  음식점 수  패션/미용소비 수  대형소비시설 수
자치구
종로구     329    176    151    85            6   6442       2207         3
중구      104    126      4    95            6   6363       4489       108
용산구     149    104      4   102            2   5693       1612         4
성동구     165     95      4    92            1   5278       1505         4
광진구      78    115     12    80            1   6227       2235         7
동대문구     21    140      6   100            0   6064       2089         8
중랑구      21    116      4   123            0   5107       2072         2
성북구      73    173      7    62            1   5789       2147        21
강북구      20    106     10   109            3   4712       1545         8
도봉구      16    118      3    97            1   3810       1441         1
노원구      24    205      9   228            2   5473       2246        23
은평구      35    185     12   136            1   5884       2289         6
서대문구     68    129      3   124            1   5008       1461        28
마포구     507    133      8   134            1   9470       2449         2
양천구      46    149      3   138            0   4744       2020         5
강서구      97    210      2   257            1   8160       2817         3
구로구      52    167      2   100            2   6073       2010        10
금천구      41     80      1    91            0   4568       1822        10
영등포구    145    165      5   144            1   8541       2629        25
동작구      44    171      3   110            0   4459       1514         2
관악구      44    196      5   151            0   6969       2477         6
서초구     416    196      3   155            4   8133       3056        28
강남구    1374    267      2   198            6  15139       5937       142
송파구      97    258     12   256            1   9811       3408        30
강동구      38    169      3   166            3   6555       2683         8

In [39]:
result.to_csv('../data/여가시설수전처리.csv')