In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/유적지수.csv')
df

   Unnamed: 0  행정 구
0         종로구    72
1          중구    20
2         노원구     8
3         송파구     8
4         용산구     7
5         서초구     6
6         강남구     6
7         동작구     5
8        동대문구     4
9         강북구     4
10       서대문구     3
11        중랑구     2
12        광진구     2
13        강서구     2
14        구로구     2
15        성북구     2
16        관악구     1
17        마포구     1
18        강동구     1
19        도봉구     1

In [4]:
df.rename(columns={'Unnamed: 0':'자치구', '행정구':'유적지 수'}, inplace=True)
df

     자치구  행정 구
0    종로구    72
1     중구    20
2    노원구     8
3    송파구     8
4    용산구     7
5    서초구     6
6    강남구     6
7    동작구     5
8   동대문구     4
9    강북구     4
10  서대문구     3
11   중랑구     2
12   광진구     2
13   강서구     2
14   구로구     2
15   성북구     2
16   관악구     1
17   마포구     1
18   강동구     1
19   도봉구     1

In [5]:
df.loc[20]=['금천구',0]

In [7]:
df.loc[21]=['성동구',0]

In [8]:
df

     자치구  행정 구
0    종로구    72
1     중구    20
2    노원구     8
3    송파구     8
4    용산구     7
5    서초구     6
6    강남구     6
7    동작구     5
8   동대문구     4
9    강북구     4
10  서대문구     3
11   중랑구     2
12   광진구     2
13   강서구     2
14   구로구     2
15   성북구     2
16   관악구     1
17   마포구     1
18   강동구     1
19   도봉구     1
20   금천구     0
21   성동구     0

In [9]:
df.loc[22]=['양천구', 0]

In [10]:
df

     자치구  행정 구
0    종로구    72
1     중구    20
2    노원구     8
3    송파구     8
4    용산구     7
5    서초구     6
6    강남구     6
7    동작구     5
8   동대문구     4
9    강북구     4
10  서대문구     3
11   중랑구     2
12   광진구     2
13   강서구     2
14   구로구     2
15   성북구     2
16   관악구     1
17   마포구     1
18   강동구     1
19   도봉구     1
20   금천구     0
21   성동구     0
22   양천구     0

In [11]:
df.loc[23]=['영등포구', 0]

In [12]:
df

     자치구  행정 구
0    종로구    72
1     중구    20
2    노원구     8
3    송파구     8
4    용산구     7
5    서초구     6
6    강남구     6
7    동작구     5
8   동대문구     4
9    강북구     4
10  서대문구     3
11   중랑구     2
12   광진구     2
13   강서구     2
14   구로구     2
15   성북구     2
16   관악구     1
17   마포구     1
18   강동구     1
19   도봉구     1
20   금천구     0
21   성동구     0
22   양천구     0
23  영등포구     0

In [13]:
df.loc[24]=['은평구', 0]

In [16]:
df.rename(columns={'행정 구':'유적지 수'}, inplace=True)
df

     자치구  유적지 수
0    종로구     72
1     중구     20
2    노원구      8
3    송파구      8
4    용산구      7
5    서초구      6
6    강남구      6
7    동작구      5
8   동대문구      4
9    강북구      4
10  서대문구      3
11   중랑구      2
12   광진구      2
13   강서구      2
14   구로구      2
15   성북구      2
16   관악구      1
17   마포구      1
18   강동구      1
19   도봉구      1
20   금천구      0
21   성동구      0
22   양천구      0
23  영등포구      0
24   은평구      0

In [17]:
df.to_csv('../data/유적지수.csv')