In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/체육 생활 이용정보_202303.csv')

In [3]:
df_seoul = df[df['CTPRVN_NM'].str.contains('서울특별시')]

In [6]:
df_seoul=df_seoul[df_seoul['BASE_YM']==202303]
df_seoul

,BASE_YM,CTPRVN_CD,CTPRVN_NM,SIGNGU_CD,SIGNGU_NM,SIGNGU_ACCTO_POPLTN_CO,MAIN_DMAND_FCLTY_FLAG_NM,MAIN_DMAND_FCLTY_NM,SIGNGU_ACCTO_FCLTY_CO,PSNBY_FCLTY_CO,PSNBY_FCL_CO_RANK_CO
69080,202303,1100000000,서울특별시,1111000000,종로구,141060,자주이용하는 공공시설 1순위,간이운동장,28,0.00020,135
69081,202303,1100000000,서울특별시,1111000000,종로구,141060,자주이용하는 민간시설 1순위,체력단련장,59,0.00042,7
69082,202303,1100000000,서울특별시,1111000000,종로구,141060,자주이용하는 공공시설 2순위,체력단련장,3,0.00002,78
69083,202303,1100000000,서울특별시,1111000000,종로구,141060,자주이용하는 민간시설 2순위,골프장/골프연습장,33,0.00023,118
69084,202303,1100000000,서울특별시,1111000000,종로구,141060,자주이용하는 공공시설 3순위,수영장,3,0.00002,38
...,...,...,...,...,...,...,...,...,...,...,...
69325,202303,1100000000,서울특별시,1174000000,강동구,459982,자주이용하는 민간시설 3순위,수영장,5,0.00001,128
69326,202303,1100000000,서울특별시,1174000000,강동구,459982,자주이용하는 공공시설 4순위,축구장,0,0.00000,204
69327,202303,1100000000,서울특별시,1174000000,강동구,459982,자주이용하는 민간시설 4순위,당구장,112,0.00024,151
69328,202303,1100000000,서울특별시,1174000000,강동구,459982,자주이용하는 공공시설 5순위,테니스장,1,0.00000,208
69329,202303,1100000000,서울특별시,1174000000,강동구,459982,자주이용하는 민간시설 5순위,체육도장,121,0.00026,98

In [15]:
df_공공간이운동장=df_seoul.loc[69080::10,:]
df_공공간이운동장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
                 'PSNBY_FCLTY_CO', 'PSNBY_FCL_CO_RANK_CO'], axis=1, inplace=True)
df_공공간이운동장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'공공간이운동장 수', 'SIGNGU_NM':'자치구'}, inplace=True)
df_공공간이운동장 = df_공공간이운동장.reindex(['자치구', '공공간이운동장 수'], axis=1)
df_공공간이운동장.set_index('자치구', inplace=True)
df_공공간이운동장

C:\Users\morat\AppData\Local\Temp\ipykernel_35612\215306022.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_공공간이운동장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
C:\Users\morat\AppData\Local\Temp\ipykernel_35612\215306022.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_공공간이운동장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'공공간이운동장 수', 'SIGNGU_NM':'자치구'}, inplace=True)

      공공간이운동장 수
자치구
종로구          28
중구            3
용산구           8
성동구           0
광진구           5
동대문구          5
중랑구           7
성북구          40
강북구          40
도봉구          78
노원구          40
은평구          27
서대문구         23
마포구         100
양천구           2
강서구          73
구로구          54
금천구          35
영등포구         64
동작구          39
관악구           3
서초구         166
강남구         110
송파구          10
강동구           5

In [16]:
df_공공수영장=df_seoul.loc[69081::10,:]
df_공공수영장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
                 'PSNBY_FCLTY_CO', 'PSNBY_FCL_CO_RANK_CO'], axis=1, inplace=True)
df_공공수영장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'민간체력단련장 수', 'SIGNGU_NM':'자치구'}, inplace=True)
df_공공수영장 = df_공공수영장.reindex(['자치구', '민간체력단련장 수'], axis=1)
df_공공수영장.set_index('자치구', inplace=True)
df_공공수영장

C:\Users\morat\AppData\Local\Temp\ipykernel_35612\1078198058.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_민간체력단련장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
C:\Users\morat\AppData\Local\Temp\ipykernel_35612\1078198058.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_민간체력단련장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'민간체력단련장 수', 'SIGNGU_NM':'자치구'}, inplace=True)

      민간체력단련장 수
자치구
종로구          59
중구          110
용산구          76
성동구          78
광진구         121
동대문구         82
중랑구          74
성북구          88
강북구          54
도봉구          63
노원구          89
은평구          97
서대문구         47
마포구         145
양천구         128
강서구         222
구로구         102
금천구          51
영등포구        143
동작구          88
관악구         127
서초구         249
강남구         396
송파구         290
강동구         115

In [17]:
df_공공체력단련장=df_seoul.loc[69082::10,:]
df_공공체력단련장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
                 'PSNBY_FCLTY_CO', 'PSNBY_FCL_CO_RANK_CO'], axis=1, inplace=True)
df_공공체력단련장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'공공체력단련장 수', 'SIGNGU_NM':'자치구'}, inplace=True)
df_공공체력단련장 = df_공공체력단련장.reindex(['자치구', '공공체력단련장 수'], axis=1)
df_공공체력단련장.set_index('자치구', inplace=True)
df_공공체력단련장

C:\Users\morat\AppData\Local\Temp\ipykernel_35612\1035820450.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_공공체력단련장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
C:\Users\morat\AppData\Local\Temp\ipykernel_35612\1035820450.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_공공체력단련장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'공공체력단련장 수', 'SIGNGU_NM':'자치구'}, inplace=True)

      공공체력단련장 수
자치구
종로구           3
중구            5
용산구           4
성동구           4
광진구           1
동대문구          7
중랑구           3
성북구           6
강북구           2
도봉구           3
노원구           1
은평구           2
서대문구          2
마포구           5
양천구           4
강서구           3
구로구           5
금천구           2
영등포구          2
동작구           3
관악구           2
서초구           4
강남구           3
송파구           5
강동구           5

In [18]:
df_골프장_골프연습장=df_seoul.loc[69083::10,:]
df_골프장_골프연습장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
                 'PSNBY_FCLTY_CO', 'PSNBY_FCL_CO_RANK_CO'], axis=1, inplace=True)
df_골프장_골프연습장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'골프/골프연습장 수', 'SIGNGU_NM':'자치구'}, inplace=True)
df_골프장_골프연습장 = df_골프장_골프연습장.reindex(['자치구', '골프/골프연습장 수'], axis=1)
df_골프장_골프연습장.set_index('자치구', inplace=True)
df_골프장_골프연습장

C:\Users\morat\AppData\Local\Temp\ipykernel_35612\939288351.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_골프장_골프연습장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
C:\Users\morat\AppData\Local\Temp\ipykernel_35612\939288351.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_골프장_골프연습장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'골프/골프연습장 수', 'SIGNGU_NM':'자치구'}, inplace=True)

      골프/골프연습장 수
자치구
종로구           33
중구            93
용산구           41
성동구           54
광진구           56
동대문구          45
중랑구           34
성북구           49
강북구           22
도봉구           36
노원구           86
은평구           48
서대문구          27
마포구           76
양천구           91
강서구          144
구로구           92
금천구           45
영등포구         127
동작구           45
관악구           49
서초구          188
강남구          432
송파구          291
강동구           80

In [19]:
df_공공수영장=df_seoul.loc[69084::10,:]
df_공공수영장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
                 'PSNBY_FCLTY_CO', 'PSNBY_FCL_CO_RANK_CO'], axis=1, inplace=True)
df_공공수영장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'공공수영장 수', 'SIGNGU_NM':'자치구'}, inplace=True)
df_공공수영장 = df_공공수영장.reindex(['자치구', '공공수영장 수'], axis=1)
df_공공수영장.set_index('자치구', inplace=True)
df_공공수영장

C:\Users\morat\AppData\Local\Temp\ipykernel_35612\305170254.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_공공수영장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
C:\Users\morat\AppData\Local\Temp\ipykernel_35612\305170254.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_공공수영장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'공공수영장 수', 'SIGNGU_NM':'자치구'}, inplace=True)

      공공수영장 수
자치구
종로구         3
중구          2
용산구         4
성동구         4
광진구         3
동대문구        3
중랑구         2
성북구         3
강북구         2
도봉구         1
노원구         2
은평구         1
서대문구        1
마포구         1
양천구         4
강서구         3
구로구         3
금천구         1
영등포구        3
동작구         3
관악구         3
서초구         5
강남구         2
송파구         3
강동구         0

In [20]:
df_민간수영장=df_seoul.loc[69085::10,:]
df_민간수영장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
                 'PSNBY_FCLTY_CO', 'PSNBY_FCL_CO_RANK_CO'], axis=1, inplace=True)
df_민간수영장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'민간수영장 수', 'SIGNGU_NM':'자치구'}, inplace=True)
df_민간수영장 = df_민간수영장.reindex(['자치구', '민간수영장 수'], axis=1)
df_민간수영장.set_index('자치구', inplace=True)
df_민간수영장

C:\Users\morat\AppData\Local\Temp\ipykernel_35612\693896549.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_민간수영장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
C:\Users\morat\AppData\Local\Temp\ipykernel_35612\693896549.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_민간수영장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'민간수영장 수', 'SIGNGU_NM':'자치구'}, inplace=True)

      민간수영장 수
자치구
종로구         0
중구          7
용산구         3
성동구         2
광진구         6
동대문구        4
중랑구         2
성북구         6
강북구         0
도봉구         2
노원구         6
은평구         4
서대문구        2
마포구         6
양천구        13
강서구        12
구로구         3
금천구         1
영등포구        5
동작구         2
관악구         4
서초구         9
강남구        11
송파구        15
강동구         5

In [21]:
df_당구장=df_seoul.loc[69087::10,:]
df_당구장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
                 'PSNBY_FCLTY_CO', 'PSNBY_FCL_CO_RANK_CO'], axis=1, inplace=True)
df_당구장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'당구장 수', 'SIGNGU_NM':'자치구'}, inplace=True)
df_당구장 = df_당구장.reindex(['자치구', '당구장 수'], axis=1)
df_당구장.set_index('자치구', inplace=True)
df_당구장

C:\Users\morat\AppData\Local\Temp\ipykernel_35612\2239659535.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_당구장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
C:\Users\morat\AppData\Local\Temp\ipykernel_35612\2239659535.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_당구장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'당구장 수', 'SIGNGU_NM':'자치구'}, inplace=True)

      당구장 수
자치구
종로구      88
중구      170
용산구      42
성동구      71
광진구     129
동대문구     83
중랑구     106
성북구     133
강북구      94
도봉구     100
노원구     110
은평구     120
서대문구     58
마포구      81
양천구     105
강서구     139
구로구     127
금천구     123
영등포구    150
동작구      80
관악구      77
서초구     210
강남구     177
송파구     206
강동구     112

In [22]:
df_체육도장=df_seoul.loc[69089::10,:]
df_체육도장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
                 'PSNBY_FCLTY_CO', 'PSNBY_FCL_CO_RANK_CO'], axis=1, inplace=True)
df_체육도장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'체육도장 수', 'SIGNGU_NM':'자치구'}, inplace=True)
df_체육도장 = df_체육도장.reindex(['자치구', '체육도장 수'], axis=1)
df_체육도장.set_index('자치구', inplace=True)
df_체육도장

C:\Users\morat\AppData\Local\Temp\ipykernel_35612\972982123.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_체육도장.drop(['BASE_YM', 'CTPRVN_CD', 'CTPRVN_NM', 'SIGNGU_CD','SIGNGU_ACCTO_POPLTN_CO', 'MAIN_DMAND_FCLTY_FLAG_NM', 'MAIN_DMAND_FCLTY_NM',
C:\Users\morat\AppData\Local\Temp\ipykernel_35612\972982123.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_체육도장.rename(columns={'SIGNGU_ACCTO_FCLTY_CO':'체육도장 수', 'SIGNGU_NM':'자치구'}, inplace=True)

      체육도장 수
자치구
종로구       23
중구        31
용산구       32
성동구       52
광진구       82
동대문구      70
중랑구       84
성북구      117
강북구       64
도봉구       83
노원구      137
은평구       98
서대문구      63
마포구       81
양천구      141
강서구      165
구로구       96
금천구       56
영등포구      88
동작구       83
관악구       85
서초구      117
강남구      147
송파구      180
강동구      121

In [23]:
result = pd.concat([df_공공간이운동장, df_공공수영장, df_민간수영장, df_체육도장, df_골프장_골프연습장, df_공공체력단련장, df_민간체력단련장, df_당구장, ], axis=1)
result

,공공간이운동장 수,공공수영장 수,민간수영장 수,체육도장 수,골프/골프연습장 수,공공체력단련장 수,민간체력단련장 수,당구장 수
자치구,,,,,,,,
종로구,28,3,0,23,33,3,59,88
중구,3,2,7,31,93,5,110,170
용산구,8,4,3,32,41,4,76,42
성동구,0,4,2,52,54,4,78,71
광진구,5,3,6,82,56,1,121,129
동대문구,5,3,4,70,45,7,82,83
중랑구,7,2,2,84,34,3,74,106
성북구,40,3,6,117,49,6,88,133
강북구,40,2,0,64,22,2,54,94
도봉구,78,1,2,83,36,3,63,100
노원구,40,2,6,137,86,1,89,110
은평구,27,1,4,98,48,2,97,120
서대문구,23,1,2,63,27,2,47,58
마포구,100,1,6,81,76,5,145,81
양천구,2,4,13,141,91,4,128,105
강서구,73,3,12,165,144,3,222,139
구로구,54,3,3,96,92,5,102,127
금천구,35,1,1,56,45,2,51,123
영등포구,64,3,5,88,127,2,143,150
동작구,39,3,2,83,45,3,88,80
관악구,3,3,4,85,49,2,127,77
서초구,166,5,9,117,188,4,249,210
강남구,110,2,11,147,432,3,396,177
송파구,10,3,15,180,291,5,290,206
강동구,5,0,5,121,80,5,115,112

In [24]:
result['수영장 수'] = result['공공수영장 수'] + result['민간수영장 수']
result['체력단련장 수'] = result['공공체력단련장 수'] + result['민간체력단련장 수']
result

,공공간이운동장 수,공공수영장 수,민간수영장 수,체육도장 수,골프/골프연습장 수,공공체력단련장 수,민간체력단련장 수,당구장 수,수영장 수,체력단련장 수
자치구,,,,,,,,,,
종로구,28,3,0,23,33,3,59,88,3,62
중구,3,2,7,31,93,5,110,170,9,115
용산구,8,4,3,32,41,4,76,42,7,80
성동구,0,4,2,52,54,4,78,71,6,82
광진구,5,3,6,82,56,1,121,129,9,122
동대문구,5,3,4,70,45,7,82,83,7,89
중랑구,7,2,2,84,34,3,74,106,4,77
성북구,40,3,6,117,49,6,88,133,9,94
강북구,40,2,0,64,22,2,54,94,2,56
도봉구,78,1,2,83,36,3,63,100,3,66
노원구,40,2,6,137,86,1,89,110,8,90
은평구,27,1,4,98,48,2,97,120,5,99
서대문구,23,1,2,63,27,2,47,58,3,49
마포구,100,1,6,81,76,5,145,81,7,150
양천구,2,4,13,141,91,4,128,105,17,132
강서구,73,3,12,165,144,3,222,139,15,225
구로구,54,3,3,96,92,5,102,127,6,107
금천구,35,1,1,56,45,2,51,123,2,53
영등포구,64,3,5,88,127,2,143,150,8,145
동작구,39,3,2,83,45,3,88,80,5,91
관악구,3,3,4,85,49,2,127,77,7,129
서초구,166,5,9,117,188,4,249,210,14,253
강남구,110,2,11,147,432,3,396,177,13,399
송파구,10,3,15,180,291,5,290,206,18,295
강동구,5,0,5,121,80,5,115,112,5,120

In [29]:
result.drop(['공공수영장 수', '민간수영장 수', '공공체력단련장 수', '민간체력단련장 수'],axis=1, inplace=True)

KeyError: "['공공수영장 수', '민간수영장 수', '공공체력단련장 수', '민간체력단련장 수'] not found in axis"

In [31]:
result.rename(columns={'공공간이운동장 수':'간이운동장 수'}, inplace=True)
result

      간이운동장 수  체육도장 수  골프/골프연습장 수  당구장 수  수영장 수  체력단련장 수
자치구
종로구        28      23          33     88      3       62
중구          3      31          93    170      9      115
용산구         8      32          41     42      7       80
성동구         0      52          54     71      6       82
광진구         5      82          56    129      9      122
동대문구        5      70          45     83      7       89
중랑구         7      84          34    106      4       77
성북구        40     117          49    133      9       94
강북구        40      64          22     94      2       56
도봉구        78      83          36    100      3       66
노원구        40     137          86    110      8       90
은평구        27      98          48    120      5       99
서대문구       23      63          27     58      3       49
마포구       100      81          76     81      7      150
양천구         2     141          91    105     17      132
강서구        73     165         144    139     15      225
구로구        54      96          92    127      6      107
금천구        35      56          45    123      2       53
영등포구       64      88         127    150      8      145
동작구        39      83          45     80      5       91
관악구         3      85          49     77      7      129
서초구       166     117         188    210     14      253
강남구       110     147         432    177     13      399
송파구        10     180         291    206     18      295
강동구         5     121          80    112      5      120

In [32]:
result.to_csv('../data/체육시설수전처리.csv')